# Generated by Django 5.0.4 on 2024-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serveraccess',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('server_name', models.CharField(choices=[('Fonepay', 'Fonepay'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('SMS', 'SMS'), ('Mobile', 'Mobile'), ('Internet', 'Internet')], max_length=50)),
                ('purpose', models.TextField()),
                ('access_by', models.CharField(max_length=255)),
                ('provided_by', models.CharField(max_length=255)),
                ('time', models.DurationField()),
            ],
        ),
    ]
