# Generated by Django 5.0.4 on 2024-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0002_serveraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSupportLog',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('issue_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Mobile Banking', 'Mobile Banking'), ('Internet Banking', 'Internet Banking'), ('Esewa', 'Esewa'), ('Fonepay', 'Fonepay'), ('Khalti', 'Khalti'), ('NPS', 'NPS'), ('SMS', 'SMS')], max_length=20)),
                ('requested_by', models.CharField(choices=[('Branch', 'Branch'), ('COD', 'COD'), ('Customer', 'Customer'), ('Others', 'Others'), ('DBD', 'DBD')], max_length=20)),
                ('issue_logged_to', models.CharField(choices=[('F1soft', 'F1soft'), ('Fonepay', 'Fonepay'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('NPS', 'NPS'), ('Others', 'Others')], max_length=20)),
                ('issue_description', models.TextField()),
                ('reference_code', models.CharField(max_length=50)),
                ('handling_person', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Processing', 'Processing'), ('Solved', 'Solved')], max_length=10)),
            ],
        ),
    ]
