# Generated by Django 5.0.4 on 2024-07-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0003_technicalsupportlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalsupportlog',
            name='handling_person',
            field=models.CharField(choices=[('Ankit Bhattarai', 'Ankit Bhattarai'), ('Aakriti Silwal', 'Aakriti Silwal'), ('Bom Bahadur BK', 'Bom Bahadur BK'), ('Bikash Devkota', 'Bikash Devkota')], max_length=30),
        ),
        migrations.AlterField(
            model_name='technicalsupportlog',
            name='issue_no',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
