# Generated by Django 5.0.4 on 2024-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0004_alter_technicalsupportlog_handling_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('task_type', models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Improvement', 'Improvement')], max_length=50)),
                ('assigned_date', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('assigned_to', models.CharField(max_length=100)),
                ('days_allocated', models.IntegerField()),
                ('solved_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
