# Generated by Django 5.0.4 on 2024-08-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0005_tasklog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='details',
            new_name='task_details',
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Improvement', 'Improvement'), ('Software', 'Software')], max_length=50),
        ),
    ]
