# Generated by Django 5.0.4 on 2024-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0006_rename_details_tasklog_task_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveraccess',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
