# Generated by Django 5.0.4 on 2024-08-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0008_alter_downtime_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Mobile Banking', 'Mobile Banking'), ('ATM', 'ATM'), ('Others', 'Others')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='serveraccess',
            name='server_name',
            field=models.CharField(choices=[('Fonepay (Live)', 'Fonepay (Live)'), ('Fonepay (Test)', 'Fonepay (Test)'), ('Esewa (Live)', 'Esewa (Live)'), ('Esewa (Test)', 'Esewa (Test)'), ('Khalti (Live)', 'Khalti (Live)'), ('Khalti (Test)', 'Khalti (Test)'), ('SMS', 'SMS'), ('Mobile (Live)', 'Mobile (Live)'), ('Mobile (Test)', 'Mobile (Test)'), ('Internet Banking (Live)', 'Internet Banking (Live'), ('Internet Banking (Test)', 'Internet Banking (Test'), ('Online Account(Test)', 'Online Account(Test)'), ('Online Account(Live)', 'Online Account(Live)'), ('Customer 360(Test)', 'Customer 360(Test)'), ('Kisan System(Live)', 'Kisan System(Live)'), ('IPS', 'IPS'), ('Connect IPS', 'Connect IPS'), ('Corporate Pay', 'Corporate Pay'), ('ECC', 'ECC'), ('Nepal Pay QR', 'Nepal Pay QR'), ('Gokyo', 'Gokyo'), ('Foneloan (Test)', 'Foneloan (Test)'), ('Foneloan (Live)', 'Foneloan (Live)'), ('Digital Chautari', 'Digital Chautari')], max_length=50),
        ),
        migrations.AlterField(
            model_name='technicalsupportlog',
            name='category',
            field=models.CharField(choices=[('Mobile Banking', 'Mobile Banking'), ('Internet Banking', 'Internet Banking'), ('Esewa', 'Esewa'), ('Fonepay', 'Fonepay'), ('Khalti', 'Khalti'), ('NPS', 'NPS'), ('SMS', 'SMS'), ('ATM', 'ATM'), ('Kisan', 'Kisan'), ('POS', 'POS'), ('Online Account', 'Online Account'), ('IPS', 'IPS'), ('ECC', 'ECC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='technicalsupportlog',
            name='handling_person',
            field=models.CharField(choices=[('Ankit Bhattarai', 'Ankit Bhattarai'), ('Aakriti Silwal', 'Aakriti Silwal'), ('Bom Bahadur BK', 'Bom Bahadur BK'), ('Bikash Devkota', 'Bikash Devkota'), ('Birendra Yadav', 'Birendra Yadav'), ('Shreya Shrestha', 'Shreya Shrestha'), ('Prakriti Gyawali', 'Prakriti Gyawali'), ('Manju Upreti', 'Manju Upreti'), ('Arjun Poudel', 'Arjun Poudel'), ('Prakash Pandey', 'Prakash Pandey'), ('Priya Gupta', 'Priya Gupta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='technicalsupportlog',
            name='issue_logged_to',
            field=models.CharField(choices=[('F1soft', 'F1soft'), ('Fonepay', 'Fonepay'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('NPS', 'NPS'), ('Peace Nepal', 'Peace Nepal'), ('Digihub', 'Digihub'), ('NCHL', 'NCHL'), ('Gokyo', 'Gokyo'), ('Others', 'Others')], max_length=20),
        ),
    ]
