# Generated by Django 5.0.4 on 2024-08-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0009_tasklog_category_alter_serveraccess_server_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='solved_date',
            new_name='live_date',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='days_allocated',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='due_date',
            field=models.CharField(choices=[('First Quarter', 'First Quarter'), ('Second Quarter', 'Second Quarter'), ('Third Quarter', 'Third Quarter'), ('Fourth Quarter', 'Fourth Quarter')], default='First', max_length=50),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='category',
            field=models.CharField(choices=[('Overall', 'Overall'), ('Board 1', 'Board 1'), ('Board 2', 'Board 2')], max_length=50),
        ),
    ]
