# Generated by Django 5.0.4 on 2024-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0010_rename_solved_date_tasklog_live_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('server_ip', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100, null=True)),
                ('storage', models.BigIntegerField()),
                ('internet_access', models.BooleanField(default=False)),
                ('request_by', models.CharField(max_length=100)),
                ('server_os', models.CharField(max_length=100)),
                ('database_ip', models.CharField(max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
