# Generated by Django 5.0.4 on 2024-09-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0011_serverip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverip',
            name='database_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serverip',
            name='request_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serverip',
            name='server_ip',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serverip',
            name='server_os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serverip',
            name='storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serverip',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
