# Generated by Django 5.0.4 on 2024-09-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0012_alter_serverip_database_ip_alter_serverip_request_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverip',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
