# Generated by Django 5.0.4 on 2024-09-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0013_serverip_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=255)),
                ('charge_deducted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_profile', models.CharField(choices=[('Bulk Registration', 'Bulk Registration'), ('Self Registration', 'Self Registration')], max_length=20)),
                ('remarks', models.CharField(choices=[('Delete and refund charge', 'Delete and refund charge'), ('Change to CustomerFinal Profile', 'Change to CustomerFinal Profile')], max_length=50)),
            ],
        ),
    ]
