# Generated by Django 5.0.4 on 2024-09-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0014_customerform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerform',
            name='charge_deducted',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerform',
            name='customer_profile',
            field=models.CharField(choices=[('Bulk Registration', 'Bulk Registration')], default='Bulk Registration', max_length=20),
        ),
    ]
