# Generated by Django 5.0.4 on 2024-09-27 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallogs', '0015_alter_customerform_charge_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerform',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
