# Generated by Django 5.0.4 on 2024-07-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0003_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_popup', models.BooleanField(default=True)),
            ],
        ),
    ]
