# Generated by Django 5.0.4 on 2024-07-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0004_portalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsetting',
            name='popup_image',
            field=models.ImageField(blank=True, null=True, upload_to='popup_images/'),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='show_image',
            field=models.BooleanField(default=True),
        ),
    ]
