# Generated by Django 5.0.4 on 2024-07-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0005_portalsetting_popup_image_portalsetting_show_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalsetting',
            name='show_image',
        ),
    ]
