# Generated by Django 5.0.4 on 2024-07-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0006_remove_portalsetting_show_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('questioned_by', models.CharField(max_length=100)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
