# Generated by Django 5.0.4 on 2024-07-30 06:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0008_digitalproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproduct',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
