# Generated by Django 5.0.4 on 2024-08-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0009_alter_digitalproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='product_pdfs/'),
        ),
    ]
