# Generated by Django 5.0.4 on 2024-12-05 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0010_digitalproduct_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_number', models.CharField(max_length=20, unique=True)),
                ('notice_name', models.CharField(max_length=255)),
                ('link_to_download', models.FileField(upload_to='notices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
            ],
        ),
    ]
