# Generated by Django 5.0.4 on 2024-12-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalapp', '0011_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
