# Generated by Django 5.0.4 on 2024-06-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcontact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
