# Generated by Django 5.0.4 on 2024-06-24 07:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcontact', '0002_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Description'),
        ),
    ]
