# Generated by Django 5.0.4 on 2024-07-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcontact', '0003_contact_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
    ]
