# Generated by Django 5.0.4 on 2024-07-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcontact', '0004_remove_contact_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('lines', models.TextField()),
            ],
        ),
    ]
