# Generated by Django 5.0.4 on 2024-09-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcontact', '0005_telephoneline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('tasks', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
