# Generated by Django 5.0.4 on 2024-09-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcontact', '0006_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_number',
            field=models.CharField(max_length=45),
        ),
    ]
