# Generated by Django 5.0.4 on 2024-10-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcontact', '0007_alter_contactinfo_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
    ]
